class CurrencyCodeModal {
  final String description;
  final String vale;

  const CurrencyCodeModal({
    required this.description,
    required this.vale,
  });
}

class CurrencyCodeData {
  static const List<CurrencyCodeModal> dataCurrencyCode = [
    CurrencyCodeModal(description: 'United Arab Emirates dirham', vale: 'AED'),
    CurrencyCodeModal(description: 'Afghan afghani', vale: 'AFN'),
    CurrencyCodeModal(description: 'Albanian lek', vale: 'ALL'),
    CurrencyCodeModal(description: 'Armenian dram', vale: 'AMD'),
    CurrencyCodeModal(
        description: 'Netherlands Antillean guilder', vale: 'ANG'),
    CurrencyCodeModal(description: 'Angolan kwanza', vale: 'AOA'),
    CurrencyCodeModal(description: 'Argentine peso', vale: 'ARS'),
    CurrencyCodeModal(description: 'Australian dollar', vale: 'AUD'),
    CurrencyCodeModal(description: 'Aruban florin', vale: 'AWG'),
    CurrencyCodeModal(description: 'Azerbaijani manat', vale: 'AZN'),
    CurrencyCodeModal(
        description: 'Bosnia and Herzegovina convertible mark', vale: 'BAM'),
    CurrencyCodeModal(description: 'Barbados dollar', vale: 'BBD'),
    CurrencyCodeModal(description: 'Bangladeshi taka', vale: 'BDT'),
    CurrencyCodeModal(description: 'Bulgarian lev', vale: 'BGN'),
    CurrencyCodeModal(description: 'Bahraini dinar', vale: 'BHD'),
    CurrencyCodeModal(description: 'Burundian franc', vale: 'BIF'),
    CurrencyCodeModal(description: 'Bermudian dollar', vale: 'BMD'),
    CurrencyCodeModal(description: 'Brunei dollar', vale: 'BND'),
    CurrencyCodeModal(description: 'Boliviano', vale: 'BOB'),
    CurrencyCodeModal(description: 'Bolivian Mvdol ', vale: 'BOV'),
    CurrencyCodeModal(description: 'Brazilian real', vale: 'BRL'),
    CurrencyCodeModal(description: 'Bahamian dollar', vale: 'BSD'),
    CurrencyCodeModal(description: 'Brunei dollar', vale: 'BTN'),
    CurrencyCodeModal(description: 'Botswana pula', vale: 'BWP'),
    CurrencyCodeModal(description: 'Belarusian ruble', vale: 'BYN'),
    CurrencyCodeModal(description: 'Belize dollar', vale: 'BZD'),
    CurrencyCodeModal(description: 'Canadian dollar', vale: 'CAD'),
    CurrencyCodeModal(description: 'Congolese franc', vale: 'CDF'),
    CurrencyCodeModal(
        description: 'WIR euro (complementary currency)', vale: 'CHE'),
    CurrencyCodeModal(description: 'Swiss franc', vale: 'CHF'),
    CurrencyCodeModal(
        description: 'CWIR franc (complementary currency)', vale: 'CHW'),
    CurrencyCodeModal(description: 'Congolese franc', vale: 'CLF'),
    CurrencyCodeModal(description: 'Unidad de Fomento', vale: 'CDF'),
    CurrencyCodeModal(description: 'Chilean peso', vale: 'CLP'),
    CurrencyCodeModal(description: 'Colombian peso', vale: 'COP'),
    CurrencyCodeModal(description: 'Unidad de Valor Real (UVR) ', vale: 'COU'),
    CurrencyCodeModal(description: 'Costa Rican colon', vale: 'CRC'),
    CurrencyCodeModal(description: 'Cuban convertible peso', vale: 'CUC'),
    CurrencyCodeModal(description: 'Cuban peso', vale: 'CUP'),
    CurrencyCodeModal(description: 'Czech koruna', vale: 'CZK'),
    CurrencyCodeModal(description: 'Djiboutian franc', vale: 'DJF'),
    CurrencyCodeModal(description: 'Danish krone', vale: 'DKK'),
    CurrencyCodeModal(description: 'Dominican peso', vale: 'DOP'),
    CurrencyCodeModal(description: 'Algerian dinar', vale: 'DZD'),
    CurrencyCodeModal(description: 'Egyptian pound', vale: 'EGP'),
    CurrencyCodeModal(description: 'Eritrean nakfa', vale: 'ERN'),
    CurrencyCodeModal(description: 'Ethiopian birr', vale: 'ETB'),
    CurrencyCodeModal(description: 'Euro', vale: 'EUR'),
    CurrencyCodeModal(description: 'Fiji dollar', vale: 'FJD'),
    CurrencyCodeModal(description: 'Falkland Islands pound', vale: 'FKP'),
    CurrencyCodeModal(description: 'Pound sterling', vale: 'GBP'),
    CurrencyCodeModal(description: 'Georgian lari', vale: 'GEL'),
    CurrencyCodeModal(description: 'Ghanaian cedi', vale: 'GHS'),
    CurrencyCodeModal(description: 'Gibraltar pound', vale: 'GIP'),
    CurrencyCodeModal(description: 'Gambian dalasi', vale: 'GMD'),
    CurrencyCodeModal(description: 'Guinean franc', vale: 'GNF'),
    CurrencyCodeModal(description: 'Guatemalan quetzal', vale: 'GTQ'),
    CurrencyCodeModal(description: 'Guyanese dollar', vale: 'GYD'),
    CurrencyCodeModal(description: 'Hong Kong dollar', vale: 'HKD'),
    CurrencyCodeModal(description: 'Honduran lempira', vale: 'HNL'),
    CurrencyCodeModal(description: 'Croatian kuna', vale: 'HRK'),
    CurrencyCodeModal(description: 'Haitian gourde', vale: 'HTG'),
    CurrencyCodeModal(description: 'Hungarian forint', vale: 'HUF'),
    CurrencyCodeModal(description: 'Indonesian rupiah', vale: 'IDR'),
    CurrencyCodeModal(description: 'Israeli new shekel', vale: 'ILS'),
    CurrencyCodeModal(description: 'Indian rupee', vale: 'INR'),
    CurrencyCodeModal(description: 'Indonesian rupiah', vale: 'IQD'),
    CurrencyCodeModal(description: 'Iraqi dinar', vale: 'IDR'),
    CurrencyCodeModal(description: 'Iranian rial', vale: 'IRR'),
    CurrencyCodeModal(
        description: 'Icelandic króna (plural: krónur)', vale: 'ISK'),
    CurrencyCodeModal(description: 'IJamaican dollar', vale: 'JMD'),
    CurrencyCodeModal(description: 'Jordanian dinar', vale: 'JOD'),
    CurrencyCodeModal(description: 'Japanese yen', vale: 'JPY'),
    CurrencyCodeModal(description: 'Kenyan shilling', vale: 'KES'),
    CurrencyCodeModal(description: 'Kyrgyzstani som', vale: 'KGS'),
    CurrencyCodeModal(description: 'Cambodian riel', vale: 'KHR'),
    CurrencyCodeModal(description: 'Indonesian rupiah', vale: 'KMF'),
    CurrencyCodeModal(description: 'Comoro franc', vale: 'IDR'),
    CurrencyCodeModal(description: 'North Korean won', vale: 'KPW'),
    CurrencyCodeModal(description: 'South Korean won', vale: 'KRW'),
    CurrencyCodeModal(description: 'Kuwaiti dinar', vale: 'KWD'),
    CurrencyCodeModal(description: 'Cayman Islands dollar', vale: 'KYD'),
    CurrencyCodeModal(description: 'Kazakhstani tenge', vale: 'KZT'),
    CurrencyCodeModal(description: 'Lao kip', vale: 'LAK'),
    CurrencyCodeModal(description: 'Lebanese pound', vale: 'LBP'),
    CurrencyCodeModal(description: 'Sri Lankan rupee', vale: 'LKR'),
    CurrencyCodeModal(description: 'Liberian dollar', vale: 'LRD'),
    CurrencyCodeModal(description: 'Lesotho loti', vale: 'LSL'),
    CurrencyCodeModal(description: 'Moroccan dirham', vale: 'MAD'),
    CurrencyCodeModal(description: 'Moldovan leu', vale: 'MDL'),
    CurrencyCodeModal(description: 'Malagasy ariary', vale: 'MGA'),
    CurrencyCodeModal(description: 'Macedonian denar', vale: 'MKD'),
    CurrencyCodeModal(description: 'Myanmar kyat', vale: 'MMK'),
    CurrencyCodeModal(description: 'Mongolian tögrög', vale: 'MNT'),
    CurrencyCodeModal(description: 'Macanese pataca', vale: 'MOP'),
    CurrencyCodeModal(description: 'Mauritanian ouguiya', vale: 'MRU'),
    CurrencyCodeModal(description: 'Mauritian rupee', vale: 'MUR'),
    CurrencyCodeModal(description: 'Maldivian rufiyaa', vale: 'MVR'),
    CurrencyCodeModal(description: 'Malawian kwacha', vale: 'MWK'),
    CurrencyCodeModal(description: 'Mexican peso', vale: 'MXN'),
    CurrencyCodeModal(
        description: 'Mexican Unidad de Inversion (UDI) ', vale: 'MXV'),
    CurrencyCodeModal(description: 'Malaysian ringgit', vale: 'MYR'),
    CurrencyCodeModal(description: 'Mozambican metical', vale: 'MZN'),
    CurrencyCodeModal(description: 'Namibian dollar', vale: 'NAD'),
    CurrencyCodeModal(description: 'Nigerian naira', vale: 'NGN'),
    CurrencyCodeModal(description: 'Nicaraguan córdoba', vale: 'NIO'),
    CurrencyCodeModal(description: 'Norwegian krone', vale: 'NOK'),
    CurrencyCodeModal(description: 'Nepalese rupee', vale: 'NPR'),
    CurrencyCodeModal(description: 'New Zealand dollar', vale: 'NZD'),
    CurrencyCodeModal(description: 'Omani rial', vale: 'OMR'),
    CurrencyCodeModal(description: 'Panamanian balboa', vale: 'PAB'),
    CurrencyCodeModal(description: 'Peruvian sol', vale: 'PEN'),
    CurrencyCodeModal(description: 'Papua New Guinean kina', vale: 'PGK'),
    CurrencyCodeModal(description: 'Philippine peso', vale: 'PHP'),
    CurrencyCodeModal(description: 'Pakistani rupee', vale: 'PKR'),
    CurrencyCodeModal(description: 'Polish złoty', vale: 'PLN'),
    CurrencyCodeModal(description: 'Paraguayan guaraní', vale: 'PYG'),
    CurrencyCodeModal(description: 'Qatari riyal', vale: 'QAR'),
    CurrencyCodeModal(description: 'Romanian leu', vale: 'RON'),
    CurrencyCodeModal(description: 'Serbian dinar', vale: 'RSD'),
    CurrencyCodeModal(description: 'Renminbi[14]', vale: 'CNY'),
    CurrencyCodeModal(description: 'Russian ruble', vale: 'RUB'),
    CurrencyCodeModal(description: 'Rwandan franc', vale: 'RWF'),
    CurrencyCodeModal(description: 'Saudi riyal', vale: 'SAR'),
    CurrencyCodeModal(description: 'Solomon Islands dollar', vale: 'SBD'),
    CurrencyCodeModal(description: 'Seychelles rupee', vale: 'SCR'),
    CurrencyCodeModal(description: 'Sudanese pound', vale: 'SDG'),
    CurrencyCodeModal(
        description: 'Swedish krona (plural: kronor)', vale: 'SEK'),
    CurrencyCodeModal(description: 'Singapore dollar', vale: 'SGD'),
    CurrencyCodeModal(description: 'Saint Helena pound', vale: 'SHP'),
    CurrencyCodeModal(description: 'Sierra Leonean leone', vale: 'SLL'),
    CurrencyCodeModal(description: 'Sierra Leonean leone', vale: 'SLE'),
    CurrencyCodeModal(description: 'Somali shilling', vale: 'SOS'),
    CurrencyCodeModal(description: 'Surinamese dollar', vale: 'SRD'),
    CurrencyCodeModal(description: 'South Sudanese pound', vale: 'SSP'),
    CurrencyCodeModal(description: 'São Tomé and Príncipe dobra', vale: 'STN'),
    CurrencyCodeModal(description: 'Salvadoran colón', vale: 'SVC'),
    CurrencyCodeModal(description: 'Syrian pound', vale: 'SYP'),
    CurrencyCodeModal(description: 'Swazi lilangeni', vale: 'SZL'),
    CurrencyCodeModal(description: 'Thai baht', vale: 'THB'),
    CurrencyCodeModal(description: 'Tajikistani somoni', vale: 'TJS'),
    CurrencyCodeModal(description: 'Turkmenistan manat', vale: 'TMT'),
    CurrencyCodeModal(description: 'Tunisian dinar', vale: 'TND'),
    CurrencyCodeModal(description: 'Tongan paanga', vale: 'TOP'),
    CurrencyCodeModal(description: 'Trinidad and Tobago dollar', vale: 'TTD'),
    CurrencyCodeModal(description: 'New Taiwan dollar', vale: 'TWD'),
    CurrencyCodeModal(description: 'Tanzanian shilling', vale: 'TZS'),
    CurrencyCodeModal(description: 'Ukrainian hryvnia', vale: 'UAH'),
    CurrencyCodeModal(description: 'Ugandan shilling', vale: 'UGX'),
    CurrencyCodeModal(description: 'United States dollar', vale: 'USD'),
    CurrencyCodeModal(description: 'United States dollar', vale: 'USN'),
    CurrencyCodeModal(
        description: 'Uruguay Peso en Unidades Indexadas (URUIURUI)',
        vale: 'UYI'),
    CurrencyCodeModal(description: 'Uruguayan peso', vale: 'UYU'),
    CurrencyCodeModal(description: 'Unidad previsional', vale: 'UYW'),
    CurrencyCodeModal(description: 'Uzbekistan som', vale: 'UZS'),
    CurrencyCodeModal(description: 'Venezuelan bolívar digital', vale: 'VED'),
    CurrencyCodeModal(description: 'Venezuelan bolívar soberano', vale: 'VES'),
    CurrencyCodeModal(description: 'Vietnamese đồng', vale: 'VND'),
    CurrencyCodeModal(description: 'Vanuatu vatu', vale: 'VUV'),
    CurrencyCodeModal(description: 'Samoan tala', vale: 'WST'),
    CurrencyCodeModal(description: 'CFA franc BEAC', vale: 'XAF'),
    CurrencyCodeModal(description: 'Silver (one troy ounce)', vale: 'XAG'),
    CurrencyCodeModal(description: 'Gold (one troy ounce)', vale: 'XAU'),
    CurrencyCodeModal(
        description: 'European Composite Unit (EURCO) (bond market unit)',
        vale: 'XBA'),
    CurrencyCodeModal(
        description: 'European Monetary Unit (E.M.U.-6) (bond market unit)',
        vale: 'XBB'),
    CurrencyCodeModal(
        description: 'European Unit of Account 9 (E.U.A.-9) (bond market unit)',
        vale: 'XBC'),
    CurrencyCodeModal(
        description: 'European Unit of Account 17 (E.U.A.-17)', vale: 'XBD'),
    CurrencyCodeModal(description: 'East Caribbean dollar', vale: 'XCD'),
    CurrencyCodeModal(description: 'Special drawing rights', vale: 'XDR'),
    CurrencyCodeModal(description: 'CFA franc BCEAO', vale: 'XOF'),
    CurrencyCodeModal(description: 'Palladium (one troy ounce)', vale: 'XPD'),
    CurrencyCodeModal(description: 'CFP franc (franc Pacifique)', vale: 'XPF'),
    CurrencyCodeModal(description: 'Platinum (one troy ounce)', vale: 'XPT'),
    CurrencyCodeModal(description: 'SUCRE', vale: 'XSU'),
    CurrencyCodeModal(description: 'Code reserved for testing', vale: 'XTS'),
    CurrencyCodeModal(description: 'ADB Unit of Account', vale: 'XUA'),
    CurrencyCodeModal(description: 'No currency', vale: 'XXX'),
    CurrencyCodeModal(description: 'Yemeni rial', vale: 'YER'),
    CurrencyCodeModal(description: 'South African rand', vale: 'ZAR'),
    CurrencyCodeModal(description: 'Zambian kwacha', vale: 'ZMW'),
    CurrencyCodeModal(description: 'Zimbabwean dollar', vale: 'ZWL'),
  ];
}
